name: app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_gen_runner: ^5.12.0
  flutter_svg: ^2.0.10
  vector_graphics: ^1.1.11
  shared_preferences: ^2.5.3
  get: ^4.7.3
  flutter_screenutil: ^5.9.3
  dio: ^5.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  generate: true

  uses-material-design: true
  fonts: 
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Roboto_Condensed
      fonts:
        - asset: assets/fonts/Roboto_Condensed/Roboto_Condensed-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Condensed/Roboto_Condensed-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto_Condensed/Roboto_Condensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto_Condensed/Roboto_Condensed-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto_Condensed/Roboto_Condensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto_Condensed/Roboto_Condensed-BoldItalic.ttf
          weight: 700
          style: italic
  assets:
    - assets/images/
    - assets/fonts/
    - assets/fonts/Roboto/
    - assets/fonts/Roboto_Condensed/

flutter_gen:
  output: lib/gen
  line_length: 80

  integrations:
    flutter_svg: true
