class CountryCode {
  final String nameCountry;
  final String dialCode;
  final String code;

  CountryCode({
    required this.nameCountry,
    required this.dialCode,
    required this.code,
  });

  static List<CountryCode> countries = [
    CountryCode(nameCountry: 'Vietnam', dialCode: '+84', code: 'VN'),
    CountryCode(nameCountry: 'United States', dialCode: '+1', code: 'US'),
    CountryCode(nameCountry: 'United Kingdom', dialCode: '+44', code: 'GB'),
    CountryCode(nameCountry: 'Australia', dialCode: '+61', code: 'AU'),
    CountryCode(nameCountry: 'India', dialCode: '+91', code: 'IN'),
    CountryCode(nameCountry: 'China', dialCode: '+86', code: 'CN'),
    CountryCode(nameCountry: 'Japan', dialCode: '+81', code: 'JP'),
    CountryCode(nameCountry: 'South Korea', dialCode: '+82', code: 'KR'),
    CountryCode(nameCountry: 'Germany', dialCode: '+49', code: 'DE'),
    CountryCode(nameCountry: 'France', dialCode: '+33', code: 'FR'),
    CountryCode(nameCountry: 'Italy', dialCode: '+39', code: 'IT'),
    CountryCode(nameCountry: 'Spain', dialCode: '+34', code: 'ES'),
    CountryCode(nameCountry: 'Netherlands', dialCode: '+31', code: 'NL'),
    CountryCode(nameCountry: 'Switzerland', dialCode: '+41', code: 'CH'),
    CountryCode(nameCountry: 'Sweden', dialCode: '+46', code: 'SE'),
    CountryCode(nameCountry: 'Norway', dialCode: '+47', code: 'NO'),
    CountryCode(nameCountry: 'Denmark', dialCode: '+45', code: 'DK'),
    CountryCode(nameCountry: 'Finland', dialCode: '+358', code: 'FI'),
    CountryCode(nameCountry: 'Russia', dialCode: '+7', code: 'RU'),
    CountryCode(nameCountry: 'Brazil', dialCode: '+55', code: 'BR'),
    CountryCode(nameCountry: 'Mexico', dialCode: '+52', code: 'MX'),
    CountryCode(nameCountry: 'Argentina', dialCode: '+54', code: 'AR'),
    CountryCode(nameCountry: 'South Africa', dialCode: '+27', code: 'ZA'),
    CountryCode(nameCountry: 'Egypt', dialCode: '+20', code: 'EG'),
    CountryCode(nameCountry: 'Turkey', dialCode: '+90', code: 'TR'),
    CountryCode(nameCountry: 'Saudi Arabia', dialCode: '+966', code: 'SA'),
    CountryCode(
      nameCountry: 'United Arab Emirates',
      dialCode: '+971',
      code: 'AE',
    ),
    CountryCode(nameCountry: 'Singapore', dialCode: '+65', code: 'SG'),
    CountryCode(nameCountry: 'Thailand', dialCode: '+66', code: 'TH'),
    CountryCode(nameCountry: 'Indonesia', dialCode: '+62', code: 'ID'),
    CountryCode(nameCountry: 'Malaysia', dialCode: '+60', code: 'MY'),
    CountryCode(nameCountry: 'Philippines', dialCode: '+63', code: 'PH'),
    CountryCode(nameCountry: 'Pakistan', dialCode: '+92', code: 'PK'),
    CountryCode(nameCountry: 'Bangladesh', dialCode: '+880', code: 'BD'),
    CountryCode(nameCountry: 'Nigeria', dialCode: '+234', code: 'NG'),
    CountryCode(nameCountry: 'Kenya', dialCode: '+254', code: 'KE'),
    CountryCode(nameCountry: 'New Zealand', dialCode: '+64', code: 'NZ'),
    CountryCode(nameCountry: 'Ireland', dialCode: '+353', code: 'IE'),
    CountryCode(nameCountry: 'Poland', dialCode: '+48', code: 'PL'),
    CountryCode(nameCountry: 'Czech Republic', dialCode: '+420', code: 'CZ'),
    CountryCode(nameCountry: 'Hungary', dialCode: '+36', code: 'HU'),
    CountryCode(nameCountry: 'Romania', dialCode: '+40', code: 'RO'),
    CountryCode(nameCountry: 'Ukraine', dialCode: '+380', code: 'UA'),
    CountryCode(nameCountry: 'Israel', dialCode: '+972', code: 'IL'),
    CountryCode(nameCountry: 'Qatar', dialCode: '+974', code: 'QA'),
    CountryCode(nameCountry: 'Kuwait', dialCode: '+965', code: 'KW'),
    CountryCode(nameCountry: 'Chile', dialCode: '+56', code: 'CL'),
    CountryCode(nameCountry: 'Colombia', dialCode: '+57', code: 'CO'),
    CountryCode(nameCountry: 'Peru', dialCode: '+51', code: 'PE'),
    CountryCode(nameCountry: 'Venezuela', dialCode: '+58', code: 'VE'),
    CountryCode(nameCountry: 'Morocco', dialCode: '+212', code: 'MA'),
    CountryCode(nameCountry: 'Algeria', dialCode: '+213', code: 'DZ'),
    CountryCode(nameCountry: 'Tunisia', dialCode: '+216', code: 'TN'),
    CountryCode(nameCountry: 'Ethiopia', dialCode: '+251', code: 'ET'),
    CountryCode(nameCountry: 'Ghana', dialCode: '+233', code: 'GH'),
    CountryCode(nameCountry: 'Sri Lanka', dialCode: '+94', code: 'LK'),
    CountryCode(nameCountry: 'Nepal', dialCode: '+977', code: 'NP'),
    CountryCode(nameCountry: 'Cambodia', dialCode: '+855', code: 'KH'),
    CountryCode(nameCountry: 'Laos', dialCode: '+856', code: 'LA'),
    CountryCode(nameCountry: 'Myanmar', dialCode: '+95', code: 'MM'),
  ];
}
